Fix `py-lint` on non-Linux platform
Small change to fix a `py-lint-rerun` error that would show up on
non-linux platform (and thus wasn't caught by CI).

Previously, `pixi run py-lint-rerun` would yield:

```
rerun_py/rerun_sdk/rerun/_tracing_session.py:177: error: "pcputimes" has no attribute "iowait"  [attr-defined]
```

Source-Ref: 6b834b41e79b885b418eeb1cbaef597198305e86